language: php
php:
  - 7.2
  - 7.3
  - 7.4
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
matrix:
  include:
    - php: 7.2
      env: dependencies=lowest
    - php: 7.3
      env: dependencies=lowest
    - php: 7.4
      env: dependencies=lowest
before_script:
  - composer self-update
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest; fi;
script:
 - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
